# Generated by Django 5.2.4 on 2025-07-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_rdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='note_coach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
